### ISSUE TITLE
Error and Bug

### ISSUE THREAD

**Issue by sshift56** [anilabhadatta/educative.io_scraper#64]
program crashes in pages with "/project" in the end of the url
![error](https://github.com/anilabhadatta/educative.io_scraper/assets/147314288/983be3ec-10ed-43ca-84b4-8f1172062f17)

https://www.educative.io/courses/javascript-in-detail-from-beginner-to-advanced/find-mutual-friends/project

Bug when resuming download, it always starts in first topic of the course.
This line causes the bug
![bug](https://github.com/anilabhadatta/educative.io_scraper/assets/147314288/d87c6833-db2d-4549-8945-39089cc479f7)
so i put a comment on it, to fix it temporarily.

**Comment by anilabhadatta** [comment]
@sshift56 
<img width="838" alt="image" src="https://github.com/anilabhadatta/educative.io_scraper/assets/48487849/b7a85f6f-2cfa-4f74-9d80-de63ac294d13">
i tested it but didn't get any bug

**Comment by anilabhadatta** [comment]
@sshift56 should be fixed, please check by recloning
also i will recommend you to redownload chrome binary and driver and delete the userdatadirectory

**Comment by sshift56** [comment]
> @sshift56 should be fixed, please check by recloning also i will recommend you to redownload chrome binary and driver and delete the userdatadirectory

I found another error, when getting "courseCollectionsJson" it never counts mini projects , but i fixed it. I added "PATH_EXTERNAL_PROJECT" in ApiUtility.py line 78.
![Capture](https://github.com/anilabhadatta/educative.io_scraper/assets/147314288/b3d9b3f7-6fb4-43af-89c8-ae1d18ee88f4)

**Comment by anilabhadatta** [comment]
@sshift56 thanks will add this
can you send me the topic link where you received this error?

**Comment by sshift56** [comment]
@anilabhadatta https://www.educative.io/module/cpp-basics

**Comment by anilabhadatta** [comment]
@sshift56 which specific topic did you get the error in this module?

**Comment by sshift56** [comment]
@anilabhadatta I got the error when getting the API Urls. This i the error
![Capture](https://github.com/anilabhadatta/educative.io_scraper/assets/147314288/34922dea-63b9-45ba-bee0-cc6484ed44e7)

I only got this error with course/module with projects/mini projects.

Module/Course with projects:
https://www.educative.io/module/cpp-basics
https://www.educative.io/module/El5jyzfnwVG47mJ67/10370001/4924227523444736

**Comment by anilabhadatta** [comment]
@sshift56 did you try cloning the latest commit?

**Comment by anilabhadatta** [comment]
@sshift56 should be fixed in latest commit, v 3.2.1, i have tested and working.

**Comment by sshift56** [comment]
@anilabhadatta another error,

https://www.educative.io/module/page/487B21tRmX24M79or/10370001/5603318673440768/5117017494913024

![Capture](https://github.com/anilabhadatta/educative.io_scraper/assets/147314288/bcde3094-3820-46f0-ba99-94cfef8d307d)

temporarily fixed it
![f](https://github.com/anilabhadatta/educative.io_scraper/assets/147314288/8085e919-dae5-402e-82a3-c5c282cd8362)

**Comment by anilabhadatta** [comment]
@sshift56 will check

**Comment by anilabhadatta** [comment]
@sshift56 fixed in latest commit

**Comment by sshift56** [comment]
> @anilabhadatta another error,
> ![Capture](https://user-images.githubusercontent.com/147314288/280501591-bcde3094-3820-46f0-ba99-94cfef8d307d.PNG)

Still encountering this error, the github repo either deleted by the owner or made it private.
So I rewrite the downloadWebpackBin fucntion, to fix it temporarily.
![Capture](https://github.com/anilabhadatta/educative.io_scraper/assets/147314288/ec838687-bc3c-4c29-8f8b-6083f0d1f4f9)

**Comment by anilabhadatta** [comment]
@sshift56 attach educativescraper.log

**Comment by anilabhadatta** [comment]
@sshift56 Please clone the latest commits before creating an issue here.
To my knowledge, the issue should be fixed but I need some data.
Always make sure to attach the EducativeScraper.log file here, I will get the information regarding the workflow.
Thanks.

**Comment by anilabhadatta** [comment]
@sshift56 
fixed in latest commit, please do git pull for new changes.
added recursive method of saving the files, should not cause issues now

**Comment by anilabhadatta** [comment]
@sshift56 @anhpho another bug fix was added related to downloadWebPackbiin v3.3.1
